#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing your project before committing'

# Run Prettier
npm run format

# Stage Changes to the fornmatted
git add . 


# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Type Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

echo 'Code looks good to be committed. Committing...'
